export const GestureActionType = {
  GO_BACK: 'goBack',
  FORWARD: 'forward',
  RELOAD_PAGE: 'reloadPage',
  STOP_LOADING: 'stopLoading',
  SCROLL_TO_TOP: 'scrollToTop',
  SCROLL_TO_BOTTOM: 'scrollToBottom',
  ZOOM_IN: 'zoomIn',
  ZOOM_OUT: 'zoomOut',
  SHOW_FIND_BAR: 'showFindBar',
  NEW_TAB: 'newTab',
  CLOSE_TAB: 'closeTab',
  CLOSE_TAB_TO_LEFT: 'closeTabToLeft',
  CLOSE_TAB_TO_RIGHT: 'closeTabToRight',
  NEXT_TAB: 'nextTab',
  PREV_TAB: 'prevTab',
  REOPEN_CLOSED_TAB: 'reopenClosedTab',
  DUPLICATE_TAB: 'duplicateTab',
  PIN_TAB: 'pinTab',
  MUTE_TAB: 'muteTab',
  NEW_WINDOW: 'newWindow',
  NEW_INCOGNITO_WINDOW: 'newIncognitoWindow',
  CLOSE_WINDOW: 'closeWindow',
  MINIMIZE_WINDOW: 'minimizeWindow',
  MAXIMIZE_WINDOW: 'maximizeWindow',
  TOGGLE_FULLSCREEN: 'toggleFullscreen',
  NONE: 'none',
} as const;

export type GestureActionType = (typeof GestureActionType)[keyof typeof GestureActionType]; 